export const products = [
    {
      id: 101,
      title: "mac book pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 1000,
      category: "laptop",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 102,
      title: "Note 7 pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 300,
      category: "phone",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 103,
      title: "Hp Elite Book",
      description: "this is simple details here for mac book pro, and nothing",
      price: 400,
      category: "laptop",
      CreationDate: "14/5/2021",
      updateDate: "20/2/2022",
    },
    {
      id: 104,
      title: "Realme Note",
      description: "this is simple details here for mac book pro, and nothing",
      price: 100,
      category: "phone",
      CreationDate: "3/2/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 105,
      title: "Hp G3",
      description: "this is simple details here for mac book pro, and nothing",
      price: 400,
      category: "laptop",
      CreationDate: "10/3/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 106,
      title: "Mac pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 800,
      category: "laptop",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 107,
      title: "Mac pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 800,
      category: "laptop",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 108,
      title: "Mac pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 800,
      category: "laptop",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
    {
      id: 109,
      title: "HP pro",
      description: "this is simple details here for mac book pro, and nothing",
      price: 800,
      category: "laptop",
      CreationDate: "14/5/2022",
      updateDate: "20/5/2022",
    },
  ];